# Generated by Django 4.0.3 on 2022-04-05 11:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_player_developer'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='developer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='shop.developer'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='game',
            name='url',
            field=models.URLField(default='hello', max_length=300, unique=True),
            preserve_default=False,
        ),
    ]
